[theme]
# Un bleu clair et doux qui s'accorde bien avec l'ardoise
primaryColor="#55B0F7"

# Le fond principal : un bleu-gris très foncé
backgroundColor="#1C202C"

# La sidebar et les conteneurs : un ton légèrement plus clair
secondaryBackgroundColor="#2A3140"

# Texte blanc pur, qui s'accorde bien avec ce fond
textColor="#FAFAFA"

font="sans serif"
