[theme]
# Un bleu vif mais pas "fluo", excellent sur le gris
primaryColor="#0A84FF" 

# Un gris foncé neutre, pas un noir absolu
backgroundColor="#222222"

# Une couleur légèrement plus claire pour les conteneurs et la sidebar
secondaryBackgroundColor="#333333"

# Un blanc légèrement cassé pour réduire le contraste
textColor="#E0E0E0"

font="sans serif"
