[theme]
# Couleur primaire
primaryColor="#55B0F7"

# Fond principal (sombre)
backgroundColor="#0E1117"

# Fond secondaire (pour la sidebar, les expanders, les conteneurs)
secondaryBackgroundColor="#1C202C"

# Couleur du texte
textColor="#FAFAFA"

# Police (optionnel, mais "sans serif" est plus propre)
font="sans serif"

