[theme]
# Couleur primaire (bleu vif pour les widgets)
primaryColor="#0A84FF"

# Fond principal (sombre)
backgroundColor="#0E1117"

# Fond secondaire (pour la sidebar, les expanders, les conteneurs)
secondaryBackgroundColor="#1C202C"

# Couleur du texte
textColor="#FAFAFA"

# Police (optionnel, mais "sans serif" est plus propre)
font="sans serif"
